### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kalbasit** [emicklei/proto-contrib#17]
Hello,

I'm trying to package this for [NixOS](https://github.com/NixOS/nixpkgs), and need to have a License in order for me to submit it. Please add one if this code is meant to be distributed.

**Comment by kalbasit** [comment]
The pull request waiting on the other side: https://github.com/NixOS/nixpkgs/pull/61261

**Comment by emicklei** [comment]
thank you for reporting this, I will add one. (the same as for /proto)

**Comment by kalbasit** [comment]
I see the License on master already :tada: 

I'm closing this issue and will release your v0.9.0.
